# Generated by Django 2.2.3 on 2019-09-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('membership_type', models.CharField(choices=[('Free', 'free'), ('Professional', 'pro'), ('Enterprise', 'ent')], default='Free', max_length=50)),
                ('stripe_plan_id', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
