# Generated by Django 2.2.3 on 2019-09-03 10:42

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '__first__'),
        ('instructors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('extra_info', models.TextField(blank=True, verbose_name='Extra Information')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(default='course_bg.jpg', upload_to='course_img/')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Start Date')),
                ('allowed_membership', models.ManyToManyField(to='memberships.Membership')),
                ('instructors', models.ManyToManyField(to='instructors.Instructor')),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Published Date')),
                ('comment', models.TextField(blank=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('extra_info', models.TextField(blank=True, verbose_name='Extra Information')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(default='lesson_bg.jpg', upload_to='lesson_img/')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='lesson_doc/')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='lesson_doc/')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='lesson_doc/')),
                ('file_4', models.FileField(blank=True, null=True, upload_to='lesson_doc/')),
                ('file_5', models.FileField(blank=True, null=True, upload_to='lesson_doc/')),
                ('video_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Video Link')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.Course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_at', models.DateTimeField(auto_now=True, verbose_name='Commented At')),
                ('msg', models.TextField(blank=True, verbose_name='Message')),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['-comment_at', 'author'],
            },
        ),
    ]
